class AddData1ToCell < ActiveRecord::Migration[5.1]
  def change
    add_column :cells, :data2, :string
    add_column :cells, :data3, :string
    add_column :cells, :data4, :string
    add_column :cells, :data5, :string
    add_column :cells, :data6, :string
    add_column :cells, :data7, :string
    add_column :cells, :data8, :string
    add_column :cells, :data9, :string
    add_column :cells, :data10, :string
    add_column :cells, :data11, :string
    add_column :cells, :data12, :string
    add_column :cells, :data13, :string
    add_column :cells, :data14, :string
    add_column :cells, :data15, :string
    add_column :cells, :data16, :string
    add_column :cells, :data17, :string
    add_column :cells, :data18, :string
    add_column :cells, :data19, :string
    add_column :cells, :data20, :string
    add_column :cells, :data21, :string
    add_column :cells, :data22, :string
    add_column :cells, :data23, :string
    add_column :cells, :data24, :string
    add_column :cells, :data25, :string
    add_column :cells, :data26, :string
    add_column :cells, :data27, :string
    add_column :cells, :data28, :string
    add_column :cells, :data29, :string
    add_column :cells, :data30, :string
    add_column :cells, :data31, :string
    add_column :cells, :data32, :string
    add_column :cells, :data33, :string
    add_column :cells, :data34, :string
    add_column :cells, :data35, :string
    add_column :cells, :data36, :string
    add_column :cells, :data37, :string
    add_column :cells, :data38, :string
    add_column :cells, :data39, :string
    add_column :cells, :data40, :string
    add_column :cells, :data41, :string
    add_column :cells, :data42, :string
    add_column :cells, :data43, :string
    add_column :cells, :data44, :string
    add_column :cells, :data45, :string
    add_column :cells, :data46, :string
    add_column :cells, :data47, :string
    add_column :cells, :data48, :string
    add_column :cells, :data49, :string
    add_column :cells, :data50, :string
    add_column :cells, :data51, :string
    add_column :cells, :data52, :string
    add_column :cells, :data53, :string
    add_column :cells, :data54, :string
    add_column :cells, :data55, :string
    add_column :cells, :data56, :string
    add_column :cells, :data57, :string
    add_column :cells, :data58, :string
    add_column :cells, :data59, :string
    add_column :cells, :data60, :string
  end
end
